Use GitHub Actions to push to Quay.io

diff --git a/.github/workflows/dockerimage.yml b/.github/workflows/dockerimage.yml
--- a/.github/workflows/dockerimage.yml
+++ b/.github/workflows/dockerimage.yml
@@ -10,32 +10,45 @@ jobs:
       fail-fast: false
       matrix:
         image:
-          - "mixpanel-proxy"
-          - "alpine-curl"
-          - "civicrm-php"
-          - "civicrm-sshd"
-          - "debian-shell"
-          - "metabase-watchdog"
-          - "mycli"
-          - "nodejs-ftp-srv"
-          - "terraform-tfnotify"
-          - "travis-cli"
-          - "ubuntu-sshd-github"
-          - "zabbix-agent"
-
+        - "alpine-curl"
+        - "azure-export"
+        - "civicrm-php"
+        - "civicrm-sshd"
+        - "debian-shell"
+        - "metabase-watchdog"
+        - "mixpanel-proxy"
+        - "mycli"
+        - "nodejs-ftp-srv"
+        - "pyupgrade"
+        - "remote-archiver"
+        - "rsyslogd"
+        - "schedule-bot"
+        - "terraform-tfnotify"
+        - "travis-cli"
+        - "ubuntu-sshd-github"
+        - "yq"
+        - "zabbix-agent"
     runs-on: ubuntu-latest
-
+    env:
+      DOCKER_REGISTRY_URL: quay.io
+      DOCKER_REGISTRY_PREFIX: "watchdogpolska"
     steps:
     - uses: actions/checkout@v1
+    - name: Pull image (best effort)
+      run: dockr pull ${DOCKER_REGISTRY_URL}/${DOCKER_REGISTRY_PREFIX}${{ matrix.image }} || echo 'Failed to pull'
     - name: Build image
-      run: docker build ${{ matrix.image }} --tag docker-registry.siecobywatelska.pl/${{ matrix.image }}:latest
+      run: docker build \
+        --cache-from ${DOCKER_REGISTRY_URL}/${DOCKER_REGISTRY_PREFIX}${{ matrix.image }}:latest \
+        --tag ${DOCKER_REGISTRY_URL}/${DOCKER_REGISTRY_PREFIX}${{ matrix.image }}:latest \
+        ${{ matrix.image }}
     - name: "Docker login"
       env:
-        DOCKER_REGISTRY_URL: docker-registry.siecobywatelska.pl
-        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
-        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+        # DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+        # DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+        DOCKER_PASSWORD: ${{ secrets.QUAY_DOCKER_PASSWORD }}
+        DOCKER_USERNAME: ${{ secrets.QUAY_DOCKER_USERNAME }}
       run: echo "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USERNAME} --password-stdin ${DOCKER_REGISTRY_URL}
       if: "github.ref == 'refs/heads/master'"
     - name: Push image
-      run: docker push docker-registry.siecobywatelska.pl/${{ matrix.image }}:latest
+      run: docker push ${DOCKER_REGISTRY_URL}/${{ matrix.image }}:latest
       if: "github.ref == 'refs/heads/master'"
