Add quay.io for pull cache

diff --git a/.github/workflows/dockerimage.yml b/.github/workflows/dockerimage.yml
--- a/.github/workflows/dockerimage.yml
+++ b/.github/workflows/dockerimage.yml
@@ -28,13 +28,16 @@ jobs:
     steps:
     - uses: actions/checkout@v1
     - name: Pull image
-      run: docker pull docker-registry.siecobywatelska.pl/${{ matrix.image }}:latest
+      run: docker pull docker-registry.siecobywatelska.pl/${{ matrix.image }}:latest || echo 'Missing image'
+    - name: Pull image from Quay.io
+      run: docker pull quay.io/watchdogpolska/${{ matrix.image }}:latest || echo 'Missing image'
     - name: Build image
       run: |
         docker build ${{ matrix.image }} \
           --tag docker-registry.siecobywatelska.pl/${{ matrix.image }}:latest \
           --cache-from docker-registry.siecobywatelska.pl/${{ matrix.image }}:latest
-    - name: "Docker login"
+          --cache-from quai.io/watchdogpolska/${{ matrix.image }}:latest
+    - name: Docker login
       env:
         DOCKER_REGISTRY_URL: docker-registry.siecobywatelska.pl
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
